openapi: 3.0.3
info:
  title: CharitySteps
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: ''
      operationId: postApiAuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: shauck@example.net
              required:
                - email
      security: []
  /api/auth/register/approve:
    post:
      summary: ''
      operationId: postApiAuthRegisterApprove
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: ''
                  example: dolorem
              required:
                - code
      security: []
  /api/auth/login:
    post:
      summary: ''
      operationId: postApiAuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: heathcote.lelia@example.org
                password:
                  type: string
                  description: ''
                  example: rerum
              required:
                - email
                - password
      security: []
  /api/auth/register/update:
    post:
      summary: ''
      operationId: postApiAuthRegisterUpdate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: iroipeqcsqq
                surname:
                  type: string
                  description: 'Must not be greater than 20 characters.'
                  example: 'y'
                sex:
                  type: string
                  description: ''
                  example: M
                  enum:
                    - M
                    - F
                password:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: Enu/6@nxCpdF
              required:
                - name
                - surname
                - sex
                - password
      security: []
  /api/user/get:
    get:
      summary: ''
      operationId: getApiUserGet
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/user/update:
    post:
      summary: ''
      operationId: postApiUserUpdate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 15 characters.'
                  example: bqaxkflfjq
                surname:
                  type: string
                  description: 'Must not be greater than 20 characters.'
                  example: gweujjcjq
                description:
                  type: string
                  description: 'Must not be greater than 200 characters.'
                  example: 'Aut dolorem labore qui maiores.'
      security: []
  /api/user/update/avatar:
    post:
      summary: ''
      operationId: postApiUserUpdateAvatar
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 12000 kilobytes.'
              required:
                - file
      security: []
  /api/user/update/email:
    post:
      summary: ''
      operationId: postApiUserUpdateEmail
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: gavin21@example.com
              required:
                - email
      security: []
  /api/user/update/email/approve:
    post:
      summary: ''
      operationId: postApiUserUpdateEmailApprove
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: ''
                  example: fugit
              required:
                - code
      security: []
tags:
  -
    name: Endpoints
    description: ''
